DDIM:
  # instantiation args
  _target_: src.pipeline_conditional_ddim.ConditionalDDIMPipeline.from_pretrained
  pretrained_model_name_or_path: /projects/deepdevpath/Anis/diffusion-comparison-experiments/experiments/bbc021_all_conc/bbc021_all_conc/bbc021_all_conc_with_dmso5/full_pipeline_save/784

  local_files_only: true
  # torch_dtype: fp16

  # other args; these "are not expected [...] and will be ignored" at instantiation
  num_inference_steps: 100
