BBBC021_comp_conc_nice_phen_high_conc_balanced_no_aug:
  _target_: torchvision.datasets.ImageFolder # currently not used; TODO: instantiate with Hydra
  root: /import/pr_deepdevpath/Anis/diffusion-comparison-experiments/datasets/dataset_test/bbc021_herbi
  #root: /projects/deepdevpath/Anis/diffusion-comparison-experiments/datasets/bbc021_latruculinb_all
  definition: 128
  normalize: [0.5, 0.5] # map to [-1, 1] for SiLU
